title: Workshop on  Software, Architecture, and Theory for Secure Systems
description: "セキュアシステムのためのソフトウェア、アーキテクチャ、理論に関するワークショップ (SATSS)"
date: Sat Oct 28 16:42:57 JST 2023
theme: jekyll-theme-minimal

# See default.html
github:
  owner_name: 
  is_project_page: false
  is_user_page: false
#announce: true
#announce_url: https://forms.gle/G8jYDktBZJRYTnYk7
#message: 第7回ワークショップ申込み<BR>(6月28日（金）17:00)
#announce_url: https://forms.gle/mwsSh6hut55noDWLA
#message: 第6回ワークショップ申込み<BR>(締め切りました)
#announce_url: https://forms.gle/mwsSh6hut55noDWLA
#message: 第6回ワークショップ申込み<BR>(締め切り：2024/5/7正午あるいは定員になり次第)
#announce_url: https://forms.gle/WN771V2hHtSBRn1y7
#message: 第4回ワークショップ申込み<BR>(締め切り：2024/3/7正午あるいは定員になり次第)
#
#announce_url: https://sc-sys.github.io/
#message: 第2回ワークショップ申込み<BR>(締め切り：2024/1/27正午あるいは定員になり次第)
#announce_url: https://forms.gle/WPVQ8qfyFVucKKuQ9
##
#announce2: true
#message2: 第3回ワークショップ申込み<BR>(締め切り：2024/1/30正午あるいは定員になり次第)
#announce_url2: https://forms.gle/fcZUF1gZssvqwDb39
##
##announce_url: https://shorturl.at/bhqt6
#message: 第1回ワークショップ申込み<BR>(締め切りました)
#message: 第1回ワークショップ申込み<BR>(締め切り:2023/12/15正午あるいは定員になり次第)
#
#announce_url: https://sc-sys.github.io/
#message: 第1回ワークショップのご案内は11月10日頃を予定しています

#
#show_downloads: true
#github:
#  zip_url: https://www.nii.ac.jp
#  tar_url: https://www.nii.ac.jp
#  repository_url: https://www.nii.ac.jp

#theme: jekyll-theme-slate
#theme: minima
#theme: minimal-mistakes-jekyll
#plugins:
#  - jekyll-feed
