title: Workshop on  Software, Architecture, and Theory for Secure Systems
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll
#theme: minima

#plugins:
#  - jekyll-feed
